
# --------------------- agent.py --------------------- #
MAX_MEM = ...
RADIUS = ...
INIT_STATE = ...
EPSILON = ...
ALPHA = ...
BETA = ...
GAMMA = ...
BATCH_SIZE = ...
FLAT_SIZE = 100

# ---------------------- env.py ---------------------- #

# --------------------- model.py --------------------- #
